# Generated by Django 2.2.2 on 2019-06-29 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='shifts_per_roster',
            field=models.IntegerField(default=0),
        ),
    ]
