# Generated by Django 3.1.3 on 2020-11-18 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20200908_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='enforce_one_shift_per_day',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='enforce_shifts_per_roster',
            field=models.BooleanField(default=True),
        ),
    ]
