# Generated by Django 4.2 on 2023-05-03 22:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0013_undo_roles_prefetch"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[],
        ),
    ]
