version: "2.4"

services:
  db:
    image: postgres:11
    volumes:
      - db:/var/lib/postgresql/data/
    networks:
      - net
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    restart: always

  rabbitmq:
    image: rabbitmq:latest
    hostname: rabbitmq1
    networks:
      - net
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    restart: always

  celery:
    image: galojix/roster-wizard:latest
    networks:
      - net
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    command: celery -A roster_project worker -l info
    depends_on:
      - db
      - rabbitmq
    restart: always

  web:
    image: galojix/roster-wizard:latest
    networks:
      - net
    ports:
      - 8000:8000
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    depends_on:
      - db
      - rabbitmq
    restart: always

volumes:
  db:

networks:
  net:
    enable_ipv6: true
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: fd01::/64
          gateway: fd01::1
