version: "2.4"

services:
  db:
    image: postgres:11
    user: 999:999
    volumes:
      - db:/var/lib/postgresql/data/
    networks:
      - net
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  rabbitmq:
    image: rabbitmq:latest
    user: 999:999
    volumes:
      - rabbitmq:/var/lib/rabbitmq/
    hostname: rabbitmq1
    networks:
      - net
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  celery:
    image: galojix/roster-wizard:latest
    user: ${USERID}:${GROUPID}
    networks:
      - net
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    depends_on:
      - db
      - rabbitmq

  web:
    image: galojix/roster-wizard:latest
    user: ${USERID}:${GROUPID}
    networks:
      - net
    ports:
      - 8000:8000
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    depends_on:
      - db
      - rabbitmq

volumes:
  db:
  rabbitmq:

networks:
  net:
    enable_ipv6: true
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: fd01::/64
          gateway: fd01::1
