version: "2.4"

services:
  db:
    env_file:
      - .env_dev_db

  web:
    env_file:
      - .env_dev_web
    build: .
    command: python /roster/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/roster

  celery:
    env_file:
      - .env_dev_web
    build: .
    command: watchmedo auto-restart --directory=./ --pattern=*.py --recursive -- celery -A roster_project worker -l INFO
    volumes:
      - .:/roster
