version: "2.4"

services:
  db:
    image: postgres:11
    env_file:
      - .env_dev_db
    volumes:
      - db:/var/lib/postgresql/data/
    networks:
      - net
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python /roster/manage.py runserver 0.0.0.0:8000
    env_file:
      - .env_dev_web
    volumes:
      - .:/roster
    networks:
      - net
    ports:
      - 8000:8000
    depends_on:
      - db
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

networks:
  net:
    enable_ipv6: true
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: fd01::/64
          gateway: fd01::1

volumes:
  db:
