version: "2.4"

services:
  db:
    image: postgres:11
    env_file:
      - .env_prod_db
    volumes:
      - db:/var/lib/postgresql/data/
      - dumps:/roster/dumps/
    networks:
      - net
  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env_prod_web
    command: gunicorn roster_project.wsgi:application --disable-redirect-access-to-syslog --error-logfile '/roster/logs/gunicorn_error.log' --access-logfile '/roster/logs/gunicorn_access.log' --workers 3 --bind 0.0.0.0:8000
    volumes:
      - static:/roster/webserver/static/
      - logs:/roster/logs/
    networks:
      - net
    expose:
      - 8000
    depends_on:
      - db
  nginx:
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - static:/roster/webserver/static/
    networks:
      - net
    depends_on:
      - web

networks:
  net:
    enable_ipv6: true
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: fd02::/64
          gateway: fd02::1

volumes:
  db:
  static:
  logs:
  dumps:
