version: "2.4"

services:
  db:
    image: postgres:11
    env_file:
      - .env_dev_db
    volumes:
      - db:/var/lib/postgresql/data/
    networks:
      - net
  web:
    build:
      context: .
      dockerfile: Dockerfile_dev
    command: python /code/manage.py runserver 0.0.0.0:8000
    env_file:
      - .env_dev_web
    volumes:
      - .:/code
    networks:
      - net
    ports:
      - 8000:8000
    depends_on:
      - db

networks:
  net:
    enable_ipv6: true
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: fd01::/64
          gateway: fd01::1

volumes:
  db:
