version: "2.4"

services:
  db:
    image: postgres:11
    env_file:
      - .env_prod_db
    volumes:
      - db:/var/lib/postgresql/data/
    networks:
      - net
  web:
    build:
      context: .
      dockerfile: Dockerfile_prod
    env_file:
      - .env_prod_web
    command: gunicorn roster_project.wsgi:application --workers 3 --bind 0.0.0.0:8000
    volumes:
      - static:/code/webserver/static/
    networks:
      - net
    expose:
      - 8000
    depends_on:
      - db
  nginx:
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - static:/code/webserver/static/
    networks:
      - net
    depends_on:
      - web

networks:
  net:
    enable_ipv6: true
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: fd02::/64
          gateway: fd02::1

volumes:
  db:
  static:
