# Generated by Django 2.2.2 on 2019-06-27 01:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_manytomany"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="available",
            field=models.BooleanField(default=True),
        ),
    ]
