# Generated by Django 2.2.3 on 2019-07-18 02:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_defaultshifts"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={"ordering": ("last_name", "first_name")},
        ),
    ]
