# Generated by Django 2.2.4 on 2019-09-02 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_daygroups'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='max_shifts',
            field=models.BooleanField(default=True),
        ),
    ]
