# Generated by Django 4.2.1 on 2023-05-29 01:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0016_alter_customuser_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                error_messages={
                    "unique": "A user with that email address already exists."
                },
                max_length=254,
                unique=True,
                verbose_name="email address",
            ),
        ),
    ]
