# Generated by Django 5.2.4 on 2025-07-29 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_customuser_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
