# Generated by Django 2.1.2 on 2018-11-04 23:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=50)),
                ('staff', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_type', models.CharField(max_length=20)),
                ('days_of_week', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ShiftRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_rule_name', models.CharField(max_length=20)),
                ('hard_constraint', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ShiftRuleRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rosters.Role')),
                ('shift_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rosters.ShiftRule')),
            ],
        ),
        migrations.CreateModel(
            name='StaffRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_rule_name', models.CharField(max_length=20)),
                ('hard_constraint', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='StaffRuleShift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rosters.Shift')),
                ('staff_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rosters.StaffRule')),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('shifts', models.ManyToManyField(to='rosters.Shift')),
                ('staff', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='staffrule',
            name='shifts',
            field=models.ManyToManyField(through='rosters.StaffRuleShift', to='rosters.Shift'),
        ),
        migrations.AddField(
            model_name='staffrule',
            name='staff',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shiftrule',
            name='roles',
            field=models.ManyToManyField(through='rosters.ShiftRuleRole', to='rosters.Role'),
        ),
        migrations.AddField(
            model_name='shiftrule',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rosters.Shift'),
        ),
    ]
