# Generated by Django 2.1.2 on 2018-11-13 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rosters', '0003_auto_20181105_0010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='days_of_week',
        ),
        migrations.AddField(
            model_name='shift',
            name='friday',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='monday',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='saturday',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='sunday',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='thursday',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='tuesday',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='wednesday',
            field=models.BooleanField(default=True),
        ),
    ]
