# Generated by Django 2.2.3 on 2019-07-18 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rosters', '0013_daygroups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='day_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rosters.DayGroup'),
        ),
        migrations.AlterField(
            model_name='staffrule',
            name='day_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rosters.DayGroup'),
        ),
    ]
