# Generated by Django 2.2.3 on 2019-07-26 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rosters', '0018_requestoff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preference',
            options={'ordering': ('staff_member', 'date', 'shift', 'like')},
        ),
        migrations.AddField(
            model_name='leave',
            name='description',
            field=models.CharField(default='Leave', max_length=15),
        ),
    ]
