# Generated by Django 2.2.3 on 2019-07-26 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rosters', '0019_leavedescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffrule',
            name='staff_rule_name',
            field=models.CharField(max_length=40),
        ),
    ]
