# Generated by Django 3.1 on 2020-08-26 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rosters', '0025_auto_20200826_0336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftrulerole',
            name='shift_rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rosters.shiftrule'),
        ),
    ]
