# Generated by Django 3.1 on 2020-08-26 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rosters', '0030_auto_20200826_0428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffruleshift',
            old_name='staff_rule',
            new_name='staffrule',
        ),
    ]
