# Generated by Django 3.1 on 2020-08-26 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rosters', '0031_auto_20200826_0742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffrule',
            old_name='staff_rule_name',
            new_name='staffrule_name',
        ),
    ]
