# Generated by Django 3.1.3 on 2020-11-19 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rosters', '0039_roster_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rostersettings',
            name='roster_name',
            field=models.CharField(default='No Roster Name Set', max_length=15),
        ),
    ]
