# Generated by Django 4.2 on 2023-05-03 22:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rosters", "0041_Permissions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shift",
            name="max_staff",
        ),
    ]
