# Generated by Django 2.2 on 2019-04-22 06:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rosters", "0006_Change TimeSlot to Shift relationship"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shiftrule",
            name="hard_constraint",
        ),
        migrations.RemoveField(
            model_name="staffrule",
            name="hard_constraint",
        ),
    ]
