# Generated by Django 2.2 on 2019-05-02 00:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rosters", "0008_add_preferences"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="role",
            name="staff",
        ),
    ]
