# Generated by Django 2.2.2 on 2019-06-27 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rosters', '0010_new_preference_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffruleshift',
            options={'ordering': ('position',)},
        ),
    ]
