# Generated by Django 2.2.3 on 2019-07-18 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("rosters", "0011_available"),
    ]

    operations = [
        migrations.CreateModel(
            name="Day",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="DayGroup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name="staffruleshift",
            options={"ordering": ("position", "shift")},
        ),
        migrations.RemoveField(
            model_name="shift",
            name="friday",
        ),
        migrations.RemoveField(
            model_name="shift",
            name="monday",
        ),
        migrations.RemoveField(
            model_name="shift",
            name="saturday",
        ),
        migrations.RemoveField(
            model_name="shift",
            name="sunday",
        ),
        migrations.RemoveField(
            model_name="shift",
            name="thursday",
        ),
        migrations.RemoveField(
            model_name="shift",
            name="tuesday",
        ),
        migrations.RemoveField(
            model_name="shift",
            name="wednesday",
        ),
        migrations.CreateModel(
            name="DayGroupDay",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="rosters.Day"
                    ),
                ),
                (
                    "day_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rosters.DayGroup",
                    ),
                ),
            ],
        ),
    ]
