# Generated by Django 2.2.3 on 2019-07-25 23:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rosters", "0017_preferencedate"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="leave",
            options={"ordering": ("staff_member", "date")},
        ),
        migrations.AddField(
            model_name="preference",
            name="like",
            field=models.BooleanField(default=True),
        ),
    ]
