# Generated by Django 3.1 on 2020-08-21 03:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rosters', '0022_leaveshifts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Preference',
            new_name='StaffRequest',
        ),
    ]
