# Generated by Django 3.1 on 2020-08-26 03:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rosters", "0027_auto_20200826_0345"),
    ]

    operations = [
        migrations.RenameField(
            model_name="shift",
            old_name="day_group",
            new_name="daygroup",
        ),
    ]
