# Generated by Django 3.1 on 2020-08-26 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rosters', '0029_auto_20200826_0405'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shiftrulerole',
            old_name='shift_rule',
            new_name='shiftrule',
        ),
    ]
