# Generated by Django 3.1 on 2020-08-26 07:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rosters", "0032_auto_20200826_0745"),
    ]

    operations = [
        migrations.RenameField(
            model_name="shiftrule",
            old_name="shift_rule_name",
            new_name="shiftrule_name",
        ),
    ]
