# Generated by Django 3.1 on 2020-08-27 01:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rosters", "0034_auto_20200827_0123"),
    ]

    operations = [
        migrations.AlterField(
            model_name="day",
            name="number",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="daygroup",
            name="name",
            field=models.CharField(max_length=20),
        ),
    ]
