# Generated by Django 3.1.2 on 2020-10-18 02:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rosters", "0035_auto_20200827_0124"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="daygroupday",
            unique_together={("daygroup", "day")},
        ),
    ]
