# Generated by Django 3.1.3 on 2020-11-18 23:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rosters", "0038_roster_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="rostersettings",
            name="not_used",
            field=models.CharField(default="Not Used", max_length=15),
        ),
    ]
