# Generated by Django 3.2.3 on 2021-06-10 01:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rosters", "0040_roster_settings"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rostersettings",
            options={"permissions": (("change_roster", "Can change rosters"),)},
        ),
    ]
