# Generated by Django 5.2.1 on 2025-07-18 03:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rosters', '0042_remove_shift_max_staff'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StaffRule',
            new_name='ShiftSequence',
        ),
    ]
