# Generated by Django 5.2.1 on 2025-07-20 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rosters', '0043_rename_staffrule_shiftsequence'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StaffRuleShift',
            new_name='ShiftSequenceShift',
        ),
    ]
