# Generated by Django 5.2.1 on 2025-07-21 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rosters', '0044_rename_staffruleshift_shiftsequenceshift'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShiftRule',
            new_name='SkillMixRule',
        ),
    ]
