# Generated by Django 5.2.1 on 2025-07-21 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rosters', '0045_rename_shiftrule_skillmixrule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skillmixrule',
            old_name='shiftrule_name',
            new_name='skillmixrule_name',
        ),
    ]
