# Generated by Django 5.2.1 on 2025-07-21 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rosters', '0046_rename_shiftrule_name_skillmixrule_skillmixrule_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShiftRuleRole',
            new_name='SkillMixRuleRole',
        ),
    ]
