# Generated by Django 5.2.1 on 2025-07-21 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rosters', '0047_rename_shiftrulerole_skillmixrulerole'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skillmixrulerole',
            old_name='shiftrule',
            new_name='skillmixrule',
        ),
    ]
