# Generated by Django 5.2.1 on 2025-07-22 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rosters', '0048_rename_shiftrule_skillmixrulerole_skillmixrule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shiftsequence',
            old_name='staffrule_name',
            new_name='shiftsequence_name',
        ),
    ]
