# Generated by Django 5.2.1 on 2025-07-22 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rosters', '0049_rename_staffrule_name_shiftsequence_shiftsequence_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shiftsequenceshift',
            old_name='staffrule',
            new_name='shiftsequence',
        ),
    ]
